name: "release"

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  release-java:
    name: "Release Java"
    strategy:
      matrix:
        version: [ '8', '11', '17', '21' ]

    runs-on: "ubuntu-latest"

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup JDK
        user: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.version }}

      - name: Maven Compile
        working-directory: java
        run: |
          mvn clean package -DskipTests